### ISSUE TITLE
LC_API: Timeout trying to establish connection to iframe

### ISSUE THREAD

**Issue by JesseWindebank** [douglascayers-org/sfdx-mass-action-scheduler#93] opened 2019-06-04 06:17 UTC
Hi all,

All of a sudden I am getting the following errors when I attempt to open a mass action record. Has anything seen this before?

Any guidance would be greatly appreciated.

Thanks,
Jesse

![2019-06-04_16-11-35](https://user-images.githubusercontent.com/39074824/58855730-1dac3000-86e4-11e9-8566-c9657b7d99d4.png)

**Comment by cchrisv** [comment] 2019-06-04 15:13
My org is having the same issue.

**Comment by douglascayers** [comment] 2019-06-05 21:34
Hi @JesseWindebank, @cchrisv,

To help me troubleshoot, please confirm you have the latest version of Mass Action Scheduler installed and have configured [Allow IFraming of Visualforce Pages with Clickjack Protection](https://github.com/douglascayers-org/sfdx-mass-action-scheduler/wiki/Pre-Requisites-Instructions#3-allow-iframing-of-visualforce-pages-with-clickjack-protection).

Also, please share screen shots / errors printed to the browser's console. In most modern browsers, you can open the developer console by right-clicking and choosing **Inspect**, then choose **Console** tab.

![image](https://user-images.githubusercontent.com/4142577/58992192-b6f44880-87af-11e9-9a1d-abbaa796ff64.png)

Thanks

**Comment by cchrisv** [comment] 2019-06-05 21:49
Howdy,
I am using the latest version. This just started happening after upgrading. I upgraded from 1.6 It is also only happening for non-admin users since the upgrade. The user affected has the Mass Action Admin permission set assigned to them.

Our org is still on Spring '19.

Here is the console.

![image](https://user-images.githubusercontent.com/26949822/58992926-1bb4a080-87ba-11e9-8fbc-0a00df6ad5f2.png)

**Comment by JesseWindebank** [comment] 2019-06-05 22:21
Hi @douglascayers 

Appreciate your response.

It appears one of the other admins must have enabled clickjack protection without me realising:

![2019-06-06_08-19-05](https://user-images.githubusercontent.com/39074824/58994439-d9c84080-8833-11e9-949b-3001aadd1ab1.png)

After whitelisting the domains you specified, the error on launch of one of the mass action records disappeared:

![2019-06-06_08-20-07](https://user-images.githubusercontent.com/39074824/58994479-f795a580-8833-11e9-9e5a-1db41b7d4547.png)

Thank you for your help.

**Comment by cchrisv** [comment] 2019-06-05 22:44
I forgot to add. We do not have clickjacking enabled. I whitelisted those domains and no change.

![image](https://user-images.githubusercontent.com/26949822/58995377-fa57b280-87c1-11e9-912e-87ad4806e361.png)

**Comment by douglascayers** [comment] 2019-06-06 01:18
Thanks @JesseWindebank for the follow up. Glad that whitelisting the Visualforce domains resolved your clickjack protection issue.

@cchrisv, thanks for the extra details. Since you don't have clickjack protection enabled, but you still got a CORS error, my next guess is to try adding the domains also to the **Security | CORS** menu in Setup according to [Use CORS to Access Salesforce Resources from Web Browsers](https://help.salesforce.com/articleView?id=extend_code_cors.htm&type=5).

**Comment by cchrisv** [comment] 2019-06-06 16:05
Unfortunately, same error for non-System Admin users.

**Comment by douglascayers** [comment] 2019-06-10 04:52
@cchrisv, since you're still experiencing the error with **non-System Admin** users, I wonder if it's due to those users not having access to the Visualforce pages themselves, too.

I just checked the [Mass Action Admin](https://github.com/douglascayers-org/sfdx-mass-action-scheduler/blob/2.2/force-app/main/default/permissionsets/Mass_Action_Admin.permissionset-meta.xml) permission set in the 2.2 release, and sure enough I've forgotten to add the Visualforce pages to it.

Please try manually granting access to the Visualforce pages to those users by either updating the **Mass Action Admin** permission set or assigning them an additional permission set that does so.

![image](https://user-images.githubusercontent.com/4142577/59173224-8dba1c00-8b11-11e9-9fd7-60f9c136f09e.png)

Thanks

**Comment by cchrisv** [comment] 2019-06-11 01:42
This fixed the issue. The permission set was also missing access to the Apex Classes. Once I provided access to those it worked. Thank you very much!

**Comment by douglascayers** [comment] 2019-06-16 02:10
Awesome, thanks for the follow up @cchrisv.

I've opened https://github.com/douglascayers-org/sfdx-mass-action-scheduler/issues/96 to add the Visualforce Pages and Apex Classes to the permission set to avoid this in the future. To be honest, I hadn't tested this use case without a System Administrator user.

**Closed by douglascayers** 2019-06-16 02:10 UTC
Labels: discussion 💬

**Comment by daveb-501commons** [comment] 2020-03-25 14:09
Just had the same issue and adding the domains fixed it
https://github.com/douglascayers-org/sfdx-mass-action-scheduler/wiki/Prerequisites#3-allow-iframing-of-visualforce-pages-with-clickjack-protection

**Comment by rhopkins-silverchef** [comment] 2020-10-29 04:03
Hi, 

I've started experiencing this error intermittently since Winter 21. I'm currently testing in a Sandbox Org, version 2.4.

I am a sys-admin. The Mass Action Admin permission set wasn't assigned to me or anyone else. I've assigned to myself just in case.

Clickjacking tick-boxes were unticked - I've ticked them now. The specified domains are whitelisted already too. VisualForce Pages mentioned above are in the permission set.

Annoyingly I didn't grab the errors from Chrome Console before another refresh and the error not occurring. I'll update here if it happens again, but posting here in case other users are experiencing with Winter 21.

Thanks,
Ross

**Comment by rhopkins-silverchef** [comment] 2020-10-29 05:22
Ok, here's the error

![image](https://user-images.githubusercontent.com/47616975/97528927-90fdc280-19fa-11eb-9af8-adbc41dbfefc.png)

**Comment by daveb-501commons** [comment] 2020-10-29 23:31
@douglascayers 

I just started experiencing the same thing with Winter 21 mentioned by @rhopkins-silverchef  - only thing that changed was the Winter 21 release upgrade.

**Comment by daveb-501commons** [comment] 2020-10-31 16:41
@douglascayers, @rhopkins-silverchef 
After further investigate it turns out the issue is related to a release update
"Enable Secure Static Resources for Lightning Components"

Looks like the fix is to change how static resources are referenced - use $Resource
https://developer.salesforce.com/docs/atlas.en-us.lightning.meta/lightning/expr_resource_value_provider.htm

I'll check out the code later to see about making the fix and submitting for review.

**Comment by rhopkins-silverchef** [comment] 2020-11-03 00:34
> @douglascayers, @rhopkins-silverchef
> After further investigate it turns out the issue is related to a release update
> "Enable Secure Static Resources for Lightning Components"
> 
> Looks like the fix is to change how static resources are referenced - use $Resource
> https://developer.salesforce.com/docs/atlas.en-us.lightning.meta/lightning/expr_resource_value_provider.htm
> 
> I'll check out the code later to see about making the fix and submitting for review.

No idea if it helps, but the workaround seems to be to open the "Configure" tab of a configuration record directly:

1. Open the MAS App
2. "Recently Viewed" View opens
3. Click on a record to open it and the Details tab opens by default
4. Click on the "Configure" tab and after some time the error will appear
5. At this point, I try a hard-refresh of my browser tab. Error will appear again
6. Copy the URL in your browser window and close the tab
7. Open a new tab and paste the URL you copied - the configure screen will open without error

**Comment by kultsh** [comment] 2021-04-21 18:49
Hi, Ran into the same issue and tried all the above solutions and still getting this error. 
![MassActionError](https://user-images.githubusercontent.com/50671826/115605640-bfc16b00-a2b0-11eb-9a2f-6d582fb5dd8a.png)

**Comment by cong-dean** [comment] 2021-05-25 03:56
@kultsh, as @daveb-501commons says, this does seem to be related to the Enable Secure Static Resources for Lightning Components release update. I had the same errors as above, and once I disabled this update, they went away.
